
FROM python:3.10.5
ENV TZ="Europe/Minsk"

WORKDIR /src/app
COPY ./requirements.txt ./requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .
RUN chmod +x /src/app/docker-entrypoint.sh
# CMD ["python", "manage.py", "runserver"]
