# Generated by Django 4.1.3 on 2022-11-20 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.domain'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parsingpattern',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.parsingpatternname'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
