# Generated by Django 4.1.3 on 2022-11-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_alter_article_author_alter_author_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingpattern',
            name='is_rss',
            field=models.BooleanField(default=False),
        ),
    ]
