# Generated by Django 4.1.3 on 2022-11-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_parsingpattern_is_rss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsingpattern',
            name='is_rss',
        ),
        migrations.AddField(
            model_name='domain',
            name='is_rss',
            field=models.BooleanField(default=True),
        ),
    ]
