# Generated by Django 4.1.3 on 2022-12-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0013_remove_comment_rating_rating_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sensitive_value',
        ),
        migrations.CreateModel(
            name='ArticleSensitiveLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensitive_valeu', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.article')),
                ('sensitive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.sensitive')),
            ],
        ),
    ]
