# Generated by Django 4.1.6 on 2023-04-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0016_article_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='desription',
            new_name='description',
        ),
    ]
