# Generated by Django 4.1.6 on 2023-05-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0017_rename_desription_domain_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesensitivelevel',
            old_name='sensitive_valeu',
            new_name='sensitive_value',
        ),
    ]
